import 'dart:math';

import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:ismart_web/common/bloc/data_state.dart';

class SmartChatBusTicketCubit extends Cubit<CommonState> {
  SmartChatBusTicketCubit() : super(CommonInitial());

  sendBusRequest({required String from, required String to}) async {
    emit(CommonLoading());
    final List<String> knownPlaces = [
      "Kathmandu",
      "Pokhara",
      "Butwal",
      "Bhairahawa",
      "Chitwan",
      "Biratnagar",
      "Bardaghat",
      "Sunauli",
      "Nepalgunj",
      "Baglung",
      "Janakpur",
      "Kushma",
      "Palpa",
      "Birgunj",
      "Kakadvitta",
      "Bhaktapur",
      "Surkhet",
      "Beni",
      "Sauraha",
      "Murgiya",
      "Lumbini",
      "Belahiya",
      "Butwal Chauraha",
      "Dharan",
      "Dhangadhi",
      "Bharatpur",
      "Delhi",
      "Dang",
      "Itahari",
      "Sunwal",
      "Arghakhanchi",
      "Dhading",
      "Palpa, tansen",
      "Manigram",
      "Krishnanagar",
      "Charnumber Jitpur",
      "Birtamode",
      "Lamachaur",
      "Syangja",
      "Butwal Buspark",
      "Waling",
      "Khaireni",
      "Syaphrubesi",
      "Bangai",
      "Taulihawa",
      "Damak",
      "Kohalpur",
      "Saljhandi",
      "Bhumahi",
      "Belbas",
      "Chandrauta",
      "Tamnagar",
      "Damauli",
      "Butwal Traffic Chowk",
      "Kapilvastu",
      "Tamghas",
      "Gaur",
      "Mahendranagar",
      "Pokhara (Baglung Bus Park)",
      "Tulsipur",
      "Jomsom",
      "Ramapur Colony",
      "Hetauda",
      "Dhulikhel",
      "Ghorahi",
      "Narayanghat",
      "Hemja",
      "Haraiya",
      "Sandhikharka",
      "Dhunche",
      "Jhapa",
      "Besisahar",
      "Ranibagiya",
      "Tikapur",
      "Nayagaun",
      "Pyuthan",
      "Jaleshwor",
      "Chhapiya",
      "Yogikuti",
      "Gorusinghe",
      "Kawasoti",
      "Manakamana (Kurintar)",
      "Gulmi",
      "Lamahi",
      "Gaighat",
      "Muktinath",
      "Dimuwa",
      "Manakamana",
      "Galyang",
      "Urlabari",
      "Rajbiraj",
      "Bhalwari",
      "Jumla",
      "Motihari",
      "Lahan",
      "Lumle/Kande",
      "Banepa",
      "Lamki",
      "Dumre",
      "Nayapul",
      "Taplejung",
      "Imiliya",
      "Bhadrapur",
      "Attariya",
      "Ilam",
      "Sunawal",
      "Tansen",
      "Kotihawa",
      "Boadgaun",
      "Bardibas",
      "Farsatikar",
      "Hatiya",
      "Bhalubang",
      "Chandaruta",
      "Nayamil",
      "Suryabinayak",
      "Sauraha Chowak",
      "Patna",
      "Burtibang",
      "Naudanda",
      "Bhurigaun",
      "Koteshwor",
      "Pipara",
      "Birgunj Buspark",
      "Darbang",
      "Kharbang",
      "Kaukhola",
      "Matihani",
      "Drivertole",
      "Ramapur",
      "Bankatta",
      "Siliguri Tenzing Norge Bus Stop",
      "Bajura",
      "Jagatpur / Kasara ",
      "Bardiya",
      "Janakpur (Ramnand Chowk)",
      "Mujaffarpur",
      "Siliguri",
      "Pashupatinagar",
      "Dule Gauda",
      "Amuwa",
      "Tandi",
      "Chappargaun",
      "Suryapura",
      "Lamachaur (Gandaki Boarding School Chowk)",
      "Dupcheshwor",
      "Beni (Baglung)",
      "Kalaiya",
      "Buddi",
      "Semlar",
      "Tourist Bus Park",
      "Pravash",
      "Rajapur (Bardiya)",
      "Buddhanagar",
      "Simara",
      "Malangawa",
      "Tatopani (Beni)",
      "Bhaktapur Bhatbhateni",
      "Shankarnagar",
      "Sarlahi (Barahathwa)",
      "Morang",
      "Bahadurgunj",
      "Bankul",
      "Inaruwa",
      "Surunga",
      "Aarughat",
      "Drivertol",
      "Basgadhi",
      "Charikot",
      "Pattharkot",
      "28 Kilo",
      "Halesi",
      "Manigaram",
      "Kolbhi",
      "Aaptari",
      "Chet Chet",
      "Bauniya",
      "Traffic Chowk, Baglung",
      "Kerkha",
      "Tamnager",
      "Gulariya (Bardiya)",
      "Mirmi",
      "Bajhang",
      "Palpa bartun",
      "Ithari",
      "Beltar",
      "Dolakha",
      "Sindhuli",
      "Khadbari",
      "Thimi",
      "Bouddha",
      "Salyan",
      "Kusma",
      "Lamjung",
      "Chisapani",
      "Mustang",
      "Kagbeni",
      "Sallaghari",
      "Bairiya",
      "Rukumkot",
      "Fikkal",
      "Pathari",
      "Talchowk",
      "Khairenitar",
      "Darvan",
      "Timure",
      "Chakchake",
      "Thakurdwar",
      "Rangeli",
      "Rukum Khalanga",
      "Belbari",
      "Birgunj Ghantaghar",
      "Mirchaiya",
      "Kanepokhari",
      "Darchula",
      "Fireline",
      "Tukuche",
      "Gwarko",
      "Chabahil",
      "Helu",
      "Sukhad",
      "Jhimjhime",
      "Manthali",
      "Sanga",
      "Zero Kilo",
      "Bayarghari",
      "Chainpur (bajhang)",
      "Chapur",
      "Prithivi Chowk",
      "Fulkharka",
      "Khara/Khala",
      "Gachiya",
      "Byu Pokhara",
      "Gulariya",
      "Chautara",
      "Dadeldhura",
      "Danda ",
      "Amarsingh Chowk",
      "Janakpur (Laxminiya)",
      "Jajarkot",
      "Dhalkebar",
      "Gorusinge",
      "Bharatpur Bus Park",
      "Baniyani",
      "Jadibuti",
      "Pipra",
      "Tribhuvan International Airport",
      "Bhaluhi",
      "Rajapur",
      "Buddha chwok",
      "Belbash",
      "Dhulabari",
      "Jorpati",
      "Lamabagar",
      "Nayaganu",
      "Janakpur (Mahendranagar)",
      "Syj-Dhangadi",
      "Dumkibas",
      "Budar",
      "Mangalapur",
      "Kulekhani",
      "Baglung New Bus Park",
      "Okhaldhunga",
      "Bodhgaya",
      "Chainpur",
      "Aabukhaireni",
      "Geetanagar",
      "Lakeside",
      "Golbazar",
      "Bhulbhule",
      "Phattepur",
      "Dipayal",
      "Bastari",
      "Jhumka",
      "Bhojpur",
      "Ngh-Bankul",
      "Tharpu",
      "Rasuwagadi",
      "Sunkhani",
      "Bidur",
      "Chaubiskoti",
      "Gokuleshwor",
      "Kaudena",
      "Budhabare",
      "Buddha Chowk",
      "Kaushaltar/Lokanthali",
      "Manglapur",
      "Khahare",
      "Kobang",
      "Nawalpur",
      "Ghodabanne",
      "Ambasha",
      "Chandranighapur",
      "Pokhariya (Sarlahi)",
      "Buttabari",
      "Bijuwar",
      "Tallubagar",
      "Katari",
      "Lokanthali",
      "Naudada",
      "Lete",
      "Hile",
      "Tehrathum",
      "Gauradaha",
      "Chatara",
      "Bungtang",
      "Kanyam",
      "Balkumari",
      "Achham (Sanfebagar)",
      "Rampur Bazar",
      "Hariban",
      "Jhakristhan",
      "Chaurjaari",
      "Bartung",
      "Tamghas`",
      "Chandragadi",
      "Rudrabeni / gulmi",
      "Janakinagar",
      "Bagdula",
      "Jatahi",
      "Birat Chowk",
      "Maldhunga",
      "Lalbandi",
      "Bhittamod",
      "Rajmarga Chauraha",
      "Diktel",
      "Satdobato",
      "Kausaltar",
      "Dana",
      "Sarlahi",
      "Bagmati (Sarlahi)",
      "Nijgadh",
      "Kopawa",
      "Babiyachaur",
      "Arunkhola",
      "Gongabu Bus Park",
      "Dhangadi (Siraha)",
      "Pokhariya",
      "Dhankuta",
      "Baglung Buspark",
      "Taal Chowk",
      "Solu",
      "Murchowk",
      "Jayanagar",
      "Yadhukaha",
      "Tatopani",
      "Satbaaz",
      "Sukhipur",
      "Nagdanda",
      "Kushmishera",
      "Bailbas (Sarlahi)",
      "Letang",
      "Mahalaxmistan",
      "Sarsiu",
      "Bhingri",
      "Sankanagar",
      "Shantibazar (Bardiya)",
      "Lalbandhi",
      "Gothgaun",
      "Jhaarbaira",
      "Jhalari",
      "Haripur",
      "Buddhi",
      "Khajuri",
      "Sorhakhutte",
      "Chandranighapur (Chandrapur)",
      "Sallibazar",
      "Swayambhu",
      "Tumlingtaar",
      "Maharajgunj",
      "Patihani",
      "Garuda",
      "Taratal",
      "Chakal chauraha",
      "Pathlaiya",
      "Raxaul",
      "Gaurigunj",
      "Nayagau",
      "Hariwan",
      "Jeetpur",
      "Gulmi Khaireni",
      "Tanahun",
      "Haridwar",
      "Chaarali",
      "Charaali",
      "Chormara",
      "Kalanki Dhungeadda (BusSewa Office)",
      "Mude",
      "Patan",
      "Nayaroad",
      "Balaju (Bhatbhateni)",
      "Rampur (Chitwan)",
      "Cancer Hospital",
      "Jomsom (Airport)",
      "Parsa",
      "Narethati",
      "Mainapokhari",
      "Falebas",
      "Tatopani (Dana)",
      "Yangon",
      "Lomanthang",
      "Raskot",
      "Ghatachaur",
      "Ramdi",
      "Marchawar",
      "Kakrahawa",
      "Dhanusadham",
      "Bhalkot",
      "Sautha",
      "Madhumalla",
      "Sukrabare",
      "Chakraghatti",
      "Barthawa",
      "Jhyalbas",
      "Koluwa",
      "Naryangad",
      "Gorkha",
      "Sisaghaat",
      "Tamaspur",
      "Sardi",
      "Tribeni",
      "Mahespur",
      "Duradadha",
      "Bhorletaar",
      "Aappipal",
      "Madi",
      "Bichaur",
      "Padebesi",
      "Solu/Salleri",
      "Ghurmi",
      "Rumjatar",
      "Rabuwa",
      "Prapcha",
      "Chyanam",
      "Katunge",
      "Thanagaun",
      "Semjong",
      "Gaira",
      "Kaule",
      "Gerkhu",
      "Saalme",
      "Khotang",
      "Kalinchowk",
      "Ladubulung",
      "Thami chagu",
      "Bhaise",
      "Lapilang",
      "Baitadi",
      "Meghauli ",
      "Trishuli",
      "Gatlang",
      "Shantibazar",
      "Parchyang",
      "Bhalche",
      "Marpak",
      "Tatopani (Rasuwa)",
      "Chilime",
      "Karmi dada",
      "Aarukharka",
      "Yarsha",
      "Thuman",
      "Bagh khoor",
      "Barchet",
      "Patikharka",
      "Thumka",
      "Brichet",
      "Kalche",
      "Larkep",
      "Taji",
      "Malangwa",
      "Siraha(kalyanpur)",
      "Mandalay",
      "Panchami",
      "Ramailo (Rangeli)",
      "Sonbarsa",
      "Kalikot manma",
      "Dailekh",
      "Bestada",
      "Pilaadi",
      "Dharampokhara",
      "Awalching",
      "Matela",
      "suyeda",
      "Sikatar",
      "Nalang",
      "Khari",
      "Jamrung",
      "Maidi",
      "Chainpur/Dhading",
      "Dhuwakot",
      "Manbu",
      "Dadagau",
      "Bhorle",
      "Rukum",
      "Shimle",
      "Bareng",
      "Kotiyaghat ",
      "Ngh Katari",
      "Liwang",
      "Belauri",
      "Bhisawa",
      "Fattepur",
      "Bhatta Gaun",
      "Satganj",
      "Bhajani",
      "Lothar",
      "Kalikasthan",
      "Khaltepani",
      "Laukahaa thadi",
      "Manarakatti",
      "Nepaltar",
      "Kechana",
      "Bengaluru",
      "Gujarat",
      "Chainabagar",
      "Kachorwa",
      "Loharpatti",
      "Dumbarwana",
      "Khalte/Sunaul Bazar",
      "Narayangadh Cancer Gate",
      "Khalanga",
      "Dudhe",
      "Kankai",
      "Betana",
      "Haraicha",
      "Salakpur",
      "Sundar Dulari",
      "Koshi Barrage",
      "Laukahi",
      "Tarahara",
      "Baalgram",
      "Duhabi",
      "Khanar",
      "Rice Mill",
      "Rampur Beltar",
      "Siduwa",
      "Kudule",
      "Ratnechaur",
      "Mangalghat",
      "Lasti",
      "Malekhu",
      "Mugling",
      "Mungling",
      "Ghasa",
      "Kathepool",
      "Marfa",
      "Mechinagar",
      "Laxmimarga",
      "Lekhnath",
      "Bhantabari",
      "Lauki",
      "Amlekhgunj",
      "Jitpur",
      "Satgunj",
      "Bhimgitthe",
      "Nwara",
      "Bokse Khola",
      "Lete Dada",
      "Lete Kalopani",
      "Pokhare Bagar",
      "Tatopani (Bhurung)",
      "Bandipur",
      "Bastipur",
      "Dharapani",
      "Mirchiya",
      "Choramara",
      "Aamiliya",
      "Kusum",
      "Samshergunj",
      "Lalgadh",
      "Khatrithati",
      "Satrasaye",
      "Duipiple",
      "Baddada",
      "Thatipokhari",
      "Borangkhola",
      "Bijaypur",
      "Balkhu",
      "Ekantakuna",
      "Gathaghar",
      "Jagate",
      "Naikap",
      "Radhe Radhe",
      "Chundevi",
      "Gatthaghar",
      "New Baneshwor",
      "Tinkune",
      "Galeshwor",
      "Parsyang",
      "Marpha",
      "Baisari",
      "Begkhola",
      "Dana Tatopani",
      "Titlang",
      "Kothihawa",
      "Arghau Chowk",
      "Chauthe",
      "Gagan Gauda",
      "Kotre",
      "Power House",
      "Bouddha (Pipal Bot)",
      "Mahendrapul",
      "Nadipur",
      "Prithivi Chwok",
      "WRC",
      "Aaiselu Kharka",
      "Bagshila",
      "Bhojpur Bajar",
      "Bhojpur Dingla",
      "Buipa",
      "Chakhewa",
      "Kharmi",
      "Khotang Panchami",
      "Nirmali",
      "Rajapaani",
      "Sakela",
      "Aaiselu Kharka (Khotang)",
      "Singati",
      "Gongar",
      "Sigati",
      "Banchare",
      "Gogarkhola",
      "Jamune",
      "Kuthli",
      "Mathilo Jagat",
      "Sakhine",
      "Sitka",
      "Totalabari",
      "Babare",
      "Pawati",
      "Tamakoshi",
      "Dattu",
      "Khochalekh",
      "Khodpe",
      "Malikaarjun",
      "Pasthi",
      "Sillegada",
      "Syaule",
      "Aarichini",
      "Dehimaadau",
      "Dhap",
      "Gurukhola",
      "Jwani",
      "Kathpate",
      "Leggaun",
      "Malikarjun",
      "Melkhet",
      "Musyachaur",
      "Pasti",
      "Sahilek",
      "Sathbaaj",
      "Vartola",
      "Musyachar",
      "Sathbhaaj",
      "Than",
      "Baldev",
      "Bamka",
      "Baghthala",
      "Deulekh",
      "Deura",
      "Dudilakhan",
      "Musyalkhan",
      "Subeda",
      "Bagmati",
      "Chandranigahpur",
      "Fulchaur",
      "Kalyanpur (Saptari)",
      "Kanchanpur (Bara)",
      "Lalgadi",
      "Rupani",
      "Chanauta",
      "Chandranigahpur (Chapur)",
      "Inruwa",
      "Kalyanpur",
      "Bhulahi",
      "Daunne",
      "Shittalnagar",
      "Sittalnagar",
      "Rajmargha Chauraha",
      "Traffic Chowk",
      "Ramapur;",
      "Tamngar",
      "Bhandara",
      "Budhachok",
      "Chandranighapur ( chandrapur)",
      "Nijhgadh",
      "Tadi",
      "Kotiwaha",
      "Bhairahawa Buddhachwok",
      "Boadgau",
      "Jhota",
      "Mauribagar",
      "Tamail",
      "Gaidakot",
      "Mukundapur",
      "Chitraban",
      "Krishi Campus",
      "Bafal (Sajha Petrol Pump)",
      "CMC Chowk",
      "Bhiman",
      "Sarojni Nagar",
      "Cancer Gate",
      "Betrawati",
      "Majhgaun",
      "Ramche",
      "Thade",
      "Battar",
      "Devighat",
      "Galchhi",
      "Ghumtibazar",
      "Mahadevghat",
      "Aamare",
      "Barahi",
      "Dhamale",
      "Kali Ghumti",
      "Keuriti",
      "Paitis Kilo",
      "Pakhure",
      "Sahakari",
      "Tigaun",
      "Bharkhu",
      "Lingling",
      "Ronga",
      "Goljung",
      "Bhagute",
      "Bhairav kot",
      "Cheuri Vanjyang",
      "Colony",
      "Deurali",
      "Gogane",
      "Sim Bhanjyang",
      "Gumchet",
      "Hakubesi",
      "Mailung",
      "Salletar",
      "Aambas",
      "Aapchaur",
      "Godrang",
      "Sanga Chaur",
      "Shimle (Rasuwa)",
      "Zero",
      "Champani",
      "Mane Gaun",
      "Nuchet",
      "Satdobato (Nuwakot)",
      "Sole",
      "Bharang Bhurung",
      "Jorchautara",
      "Kagune",
      "Samari",
      "Tangjha",
      "Tikadhum",
      "Hawa Dadha",
      "Pajung",
      "Manigaun",
      "Ghormu",
      "Jibjibe",
      "Khalchet",
      "Langbu",
      "Thangdur",
      "Ambash",
      "Yubra",
      "Dandagaun",
      "Gabis",
      "Gerkhutar",
      "Dhade",
      "Mendogaun",
      "Bhatta Khola",
      "Chipleti",
      "Gadi",
      "Nalgaun",
      "Panchase",
      "Saili Bhatti",
      "Borey",
      "Chhap",
      "Chogate",
      "Lachyang",
      "Nuwakot",
      "Phalate",
      "Sharamthali",
      "Fasang",
      "Gastri",
      "Kimtang",
      "Maur",
      "Pachet",
      "Satyadevi",
      "Dhansar",
      "Urleni",
      "Dangsing",
      "Gorsang",
      "Jantare",
      "Khadka Bhanjyang",
      "Khanal Gaun",
      "Linglinge",
      "Majuwa",
      "Phaleto",
      "Bhimad",
      "Padampur",
      "Ratnanagar",
      "Godeta",
      "Birendra Bazar",
      "Bisanpur",
      "Dhalkeshwor",
      "Dharapani (Dhanusha)",
      "Potiha",
      "Bishanpur",
      "Choharwa",
      "Dhangadi",
      "Siraha bazar",
      "Bhalawari",
      "Mangalbare",
      "Chhaptari",
      "charang",
      "Chhusang (Chaile)",
      "Ghami",
      "Ghiling",
      "Sangbuchhe",
      "Summer",
      "Tangbe",
      "Jomsom (Kathe Pul)",
      "Panchthar",
      "Phidim",
      "Basundhara",
      "Narayantar",
      "Sukedhara",
      "Hallan Chowk",
      "Dolalghat",
      "Bakulahar",
      "Nipani",
      "Muglin",
      "Milan Chowk",
      "Paras Bus Park",
      "Parsa Bazar",
      "Bahunbeshi",
      "Dhikure",
      "Phedibesi",
      "Saatbise",
      "Samundratar",
      "Bhaluwahi",
      "Dakaha",
      "Dudhauli",
      "Jagadi",
      "Khaniya",
      "Ranibas",
      "Bhaluwai",
      "Bijaypur(Rautahat)",
      "Himalibash",
      "Maulapur",
      "Tamaghadi Gate",
      "Shivnagar",
      "Basantapur",
      "Bhaunne",
      "Jhiljhile",
      "Bariyarpatti",
      "Bhagwanpur",
      "Kokshi",
      "garcha",
      "Manghar",
      "Khurkot",
      "Rastra Bank Chowk",
      "Seti Khola",
      "Baherghari",
      "Fedi Khola",
      "Himalaya Petrol Pump",
      "Mahendrapool",
      "Taal chwok",
      "Chandanpur",
      "Sirthauli",
      "Harsahi",
      "Sarlahi, lalbandhi",
      "Balaju (Ganga Hall)",
      "Gaushala",
      "Kalanki (Bussewa Office)",
      "Machhapokhari",
      "Samakhusi Chowk",
      "Swayambu",
      "Gargare",
      "Chinchu",
      "Raadi",
      "Bake (Sarlahi)",
      "Fuljhor",
      "Ranigunj",
      "Kanchibajar",
      "Pipra (Mahottari)",
      "Sanischare",
      "Gogabu Buspark",
      "Sinamangal Cargo",
      "Kalanki (Dhungeadda)",
      "Matiarwa",
      "Kandebas",
      "Khaulara",
      "Traffic Chowk Baglung",
      "Ram Rekha",
      "Tiplang",
      "Byeu Pokhara",
      "Bartun",
      "Taamnagar",
      "Thakalichowk",
      "Ratodhunga",
      "Simalchaur",
      "Singha",
      "Tatopani (Darbang)",
      "Devisthan",
      "Dumahi",
      "Kadebas",
      "Kakri",
      "Khalaura",
      "Khawang Bazar",
      "Lukum",
      "Nisi",
      "Rijal Chowk",
      "Simana",
      "Bobang",
      "Dhorpatan",
      "Dogadi",
      "Dunipadhera",
      "Falekghar",
      "Galyang (Baglung)",
      "Jhiwa Khola",
      "Kafalthuta",
      "Khoullar",
      "Manewa",
      "Rijalchowk",
      "Saikhola`",
      "Ghokhani",
      "Gitthakot",
      "Saak",
      "Ship",
      "Siwang",
      "Balewa",
      "Rankhani",
      "Danda, kawasoti, dumkibas",
      "Jhumak",
      "Louki",
      "Chakrapath",
      "Sukkhad",
      "Bauniyara",
      "Katarniya",
      "Masuriya",
      "Fuljor",
      "Beluwa",
      "Khairapur",
      "Kothiyaghat",
      "Lalibazar",
      "Pachasa",
      "Sitlabajar",
      "Tapra",
      "Woralibazar",
      "Chhinchu",
      "Samsergunj",
      "Aagaiya",
      "Khorsani",
      "Chorba",
      "Fakling",
      "Sulichaur",
      "Bharda",
      "Kanchanpur",
      "Mauli",
      "Khorsane",
      "Rambapur",
      "Rupmi",
      "Harmi Chaur",
      "Birga Bhustung",
      "Ngadi",
      "Chauthe Chowk",
      "Kothre",
      "Gongabu",
      "Barne",
      "Harkate",
      "Bariyarpur",
      "Simrangadh",
      "Kathariya",
      "Jhunkunwa",
      "Santapur",
      "Sukdev Chowk",
      "Ramdi (Malungwa)",
      "Pakhribas",
      "Pyauli",
      "Tiwari Bhanjyang",
      "Daiji",
      "Bani",
      "Bhasi",
      "Amliya",
      "Chanaura",
      "Gorusing",
      "Kalakot",
      "Rihar",
      "Chaumala",
      "Chaubala",
      "Aarebhanjyang",
      "Helui",
      "Ramadi",
      "Chandranigapur",
      "Mahendranagar (Janakpur)",
      "Amleshgunj",
      "Manhari",
      "Dumkibash",
      "rajhar",
      "Phulparasi",
      "Buddhachowck",
      "Madhauliya",
      "Pathardada",
      "Shankhanagar",
      "Thutipeepal",
      "Janakinager",
      "Kotihwa",
      "Bahadurgung",
      "Muggiya",
      "Nayamill",
      "Divertoal",
      "Gulmi Tamghas",
      "Imliya",
      "Pippara",
      "Ghantaghar",
      "Cherneta",
      "Jaspur",
      "Jumri",
      "Kathar",
      "Auraiya",
      "Rajpur",
      "Sakhuwa Dhamaura",
      "Benauli",
      "Piparpati",
      "Bhulke",
      "Dulari Chowk",
      "Sundarpur",
      "Mahadevphat",
      "Keurini",
      "Chandi Danda",
      "Kot Ghaderi",
      "Sakti Mabi",
      "Shiva Mandir",
      "Balara",
      "Dhungrekhola",
      "Solti",
      "Udyapur",
      "Pahalmanpur",
      "Shankarpur",
      "Naya Road",
      "Bakchaura",
      "Belhi",
      "Pathalaiya, birgunj",
      "Bhagawanpur",
      "channhi",
      "Maheshbari",
      "nirsaiya",
      "pariyarpur",
      "Patlaiya",
      "thaarapatti",
      "Amiliya tulsipur",
      "Aurahi",
      "Bakhri",
      "Ekdara",
      "Ramgopalpur",
      "Sarpallo",
      "Sabhagriha Chowk",
      "Beldiya",
      "Dalldale",
      "Tinkauriya",
      "Baguwa",
      "Patnali",
      "Bhimgithe",
      "Hadikhola",
      "Kanabagar",
      "jiwakhola",
      "Kavra",
      "Pokharibagar",
      "Sitabazar",
      "Himali",
      "Gawai",
      "Basene chowk",
      "Bhojad",
      "Lama Tole",
      "Malpot Chowk",
      "Narayangarh",
      "Ghodaghodi",
      "Hyderabad",
      "Lucknow",
      "Ahmedabad",
      "Rajkot",
      "Surat",
      "Domai",
      "Ghorkhani",
      "Githakoth",
      "Hasibang",
      "Khabangbagar",
      "Pedibazar",
      "Simli",
      "Bhuwalichowk",
      "Khap Ghiura",
      "Narkatiya",
      "Bisrampur",
      "Chetnagar",
      "Madhopur",
      "Malahitol",
      "Samanpur",
      "Sindhureghari",
      "Basbariya",
      "Simraungadh",
      "Kadmaha",
      "Kathauna",
      "Aapraha",
      "Chaughada",
      "Aauraiya",
      "Babargunj",
      "Barampuri (Sarlahi)",
      "bhade ",
      "chunarhawa",
      "Michaiya",
      "Rupni",
      "Sitapur",
      "Shreenagar",
      "Baidi",
      "Khajura",
      "Salaghari",
      "Devkota Chowk",
      "Thutipipal",
      "Khawang",
      "Taksera",
      "Bhathiyan",
      "Raghunathpur",
      "Sabaila",
      "Buddhnagar",
      "Dokebajar",
      "Arghu Chowk",
      "Nabi",
      "Kalanki",
      "Ramailo",
      "Shivagunj",
      "Rajghat",
      "Juropani",
      "Lakhanpur",
      "Dangihat",
      "Ambot",
      "Bindhyabasini",
      "Dobilla",
      "Ghatte Khola",
      "Hari Chowk",
      "Hemja (Milan Chowk)",
      "Kande",
      "Lumle",
      "Patichaur",
      "Srijana Chowk",
      "Suikhet",
      "Yemdi (Hemja)",
      "Galchi",
      "Kahukhola",
      "Belsot",
      "Saatdobato(nuwakot)",
      "Jiling",
      "Banuwa Ghumti",
      "Gumbu Dada",
      "Pahirebesi",
      "Ghalegadi",
      "Majhgaun (Gerkhu)",
      "Narayanghad",
      "Singa",
      "Bhagle",
      "Chhinkhet",
      "Daune",
      "Kunakhet",
      "Lagim",
      "Pipal",
      "Pipalpokhara",
      "Charali",
      "Khursane",
      "Badera",
      "Ghodaha",
      "Kataiya",
      "Madhawaliya",
      "Padsari",
      "Kandebass ",
    ];
    final bestFromLocation = getBestMatch(from, knownPlaces);
    final bestToLocation = getBestMatch(to, knownPlaces);
    emit(
      CommonStateSuccess(
        data: {"from": bestFromLocation, "to": bestToLocation},
      ),
    );
  }

  String getBestMatch(String input, List<String> places) {
    double highestScore = 0.0;
    String bestMatch = '';

    for (String place in places) {
      double score = jaroWinkler(input.toLowerCase(), place.toLowerCase());
      if (score > highestScore) {
        highestScore = score;
        bestMatch = place;
      }
    }
    return bestMatch;
  }

  double jaro(String s1, String s2) {
    if (s1.isEmpty || s2.isEmpty) return 0.0;

    final int matchDistance = (s1.length / 2).floor() - 1;
    final List<bool> s1Matches = List.filled(s1.length, false);
    final List<bool> s2Matches = List.filled(s2.length, false);

    int matches = 0;
    int transpositions = 0;

    for (int i = 0; i < s1.length; i++) {
      final int start = max(0, i - matchDistance);
      final int end = min(s2.length - 1, i + matchDistance);

      for (int j = start; j <= end; j++) {
        if (s2Matches[j]) continue;
        if (s1[i] != s2[j]) continue;
        s1Matches[i] = true;
        s2Matches[j] = true;
        matches++;
        break;
      }
    }

    if (matches == 0) return 0.0;

    int k = 0;
    for (int i = 0; i < s1.length; i++) {
      if (!s1Matches[i]) continue;
      while (!s2Matches[k]) k++;
      if (s1[i] != s2[k]) transpositions++;
      k++;
    }

    final double jaroScore =
        (matches / s1.length +
            matches / s2.length +
            (matches - transpositions / 2.0) / matches) /
        3.0;
    return jaroScore;
  }

  double jaroWinkler(String s1, String s2) {
    const double prefixWeight = 0.1;

    final double jaroDistance = jaro(s1, s2);
    int prefixLength = 0;

    for (int i = 0; i < min(s1.length, s2.length); i++) {
      if (s1[i] == s2[i])
        prefixLength++;
      else
        break;
    }

    final double score =
        jaroDistance + prefixWeight * prefixLength * (1 - jaroDistance);
    return score * 100; // Convert score to a range between 0 and 100
  }
}
